### PR TITLE
Add respondent home system test

### PR DESCRIPTION
**Pull request by jcox-dev**
# Motivation and Context

Adds the simple healtcheck system test for respondent home ui. 

# How to test?

- Clone and checkout the docker branch linked in the PR below
- `make pull && make up` in the docker directory (should bring up a tagged version of respondent home ui - a Python app)
- Run the system tests with behave: `pipenv run behave system_tests/features`

# Links

- ~[Add to docker PR](https://github.com/ONSdigital/ras-rm-docker-dev/pull/65)~ (now on master)
- [Python app PR](https://github.com/ONSdigital/respondent-home-ui/pull/22)

### CODE REVIEW

**Comment by jcox-dev** [comment]
[Dev task 7: EXT: Access eQ social survey (RH) (???)](https://trello.com/c/SwkUMf9O/99-dev-task-7-ext-access-eq-social-survey-rh)

**Comment by jcox-dev** [comment]
@tej99 flakey tests more likely than RH having anything to do with SM tests surely?

**Comment by jcox-dev** [comment]
On hold until the [docker PR](https://github.com/ONSdigital/ras-rm-docker-dev/pull/65) is merged.

@tej99 there'll be a separate PR for RH functionality.

**Comment by jcox-dev** [comment]
@tej99 this should be good to go in now.

**Comment by gemmai95** [comment]
@jcox-dev Does this mean social acceptance tests are being added to this repo too?

**Comment by jcox-dev** [comment]
@gemmai95 I would have thought so. Is there concern around adding the acceptance tests for social here?

**Comment by benjefferies** [comment]
Maybe we should start writing the acceptance tests in https://github.com/ONSdigital/respondent-home-ui?

**Comment by jcox-dev** [comment]
@benjefferies that's currently where the [new Python app](https://github.com/ONSdigital/respondent-home-ui/pull/22) is being developed. Possible. Perhaps they would benefit more if we did something similar to the integration test pattern of other repos. Any acceptance tests (for user stories) makes more sense to be in here though.

**Pull request merged**
