### PR TITLE
Enter UAC Code

### PR DESCRIPTION
**Pull request by jcox-dev**
# Motivation and Context

New social acceptance test for entering a UAC as a respondent into Respondent Home.

# What has changed

Added feature file, steps, and RH page. 
Tweaked some return statements.
Added UAC to context.
Added EQ_URL as a config variable.

# How to test?

`make TEST_TARGET=acceptance_tests/features/social_enter_uac.feature social_acceptance_tests`

# Links

https://trello.com/c/eotv2PRA

### CODE REVIEW

**Comment by jcox-dev** [comment]
[EXT: Enter UAC Code](https://trello.com/c/eotv2PRA/220-ext-enter-uac-code)

**Comment by jcox-dev** [comment]
@benjefferies all this is being tested within RH already. This was more to increase confidence and visibility of RH -> eQ. Is the idea to deprecate this entire repo in favour of services running their own acceptance tests?

**Comment by shahi645** [comment]
@liamtoozer Do capabilities want to merge this?

**Comment by jcox-dev** [comment]
Closing for now as we have more tests that do the same thing in the RH repo.

**Pull request closed without merging**
